version: '3.7'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - db-data:/db
    ports:
      - 27017:27017
    restart: always
    command: --quiet
  notebook:
    build:
      context: ./docker
    container_name: notebook
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      MONGO_INITDB_ROOT_USERNAME: admin 
      MONGO_INITDB_ROOT_PASSWORD: password 
      DB_NAME: airbnb-data
      DB_USER: sparkUser
      DB_PASSWORD: password
    ports:
       - 8888:8888
    restart: always
    depends_on:
      - mongo
    volumes:
      - ./app/:/home/jovyan/work
    networks:
      - localnet

  spark-master:
    image: bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - 9090:8080
      - 7077:7077
  spark-worker-1:
    image: bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
  spark-worker-2:
    image: bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
volumes:
  db-data:

networks:
    localnet:
        attachable: true
